// <auto-generated />
using System;
using EF_Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Project.Migrations
{
    [DbContext(typeof(HotelSystemDbContext))]
    partial class HotelSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Project.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("GuestID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD85B40559");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EF_Project.Models.BookingRoom", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int>("AssignedEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedEmployeeID");

                    b.Property<string>("AssignedEmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookingId", "RoomId")
                        .HasName("PK__BookingR__F0BD795C253AD10F");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingRooms");
                });

            modelBuilder.Entity("EF_Project.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04FF1D6C33FAF");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EF_Project.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GuestId")
                        .HasName("PK__Guests__0C423C32ED60EC17");

                    b.HasIndex(new[] { "Email" }, "UQ__Guests__A9D10534409D4D96")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("EF_Project.Models.HotelRanking", b =>
                {
                    b.Property<int>("RankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RankingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankingId"));

                    b.Property<string>("GuestFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("GuestID");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.HasKey("RankingId")
                        .HasName("PK__HotelRan__018A6AF9D54B72A0");

                    b.HasIndex("GuestId");

                    b.ToTable("HotelRanking", (string)null);
                });

            modelBuilder.Entity("EF_Project.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("GuestFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A58AAE12E4B");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EF_Project.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RoomTypeID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__32863919C7009B3E");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex(new[] { "RoomNumber" }, "UQ__Rooms__AE10E07A16E4CDC7")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EF_Project.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeId")
                        .HasName("PK__RoomType__BCC896112EFD5BD4");

                    b.HasIndex(new[] { "TypeName" }, "UQ__RoomType__D4E7DFA83681CFA0")
                        .IsUnique();

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("EF_Project.Services.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB0EAD6805C0A");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EF_Project.Services.ServiceUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime?>("UsageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UsageId")
                        .HasName("PK__ServiceU__29B197C0075821DD");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceUsage", (string)null);
                });

            modelBuilder.Entity("EF_Project.Models.Booking", b =>
                {
                    b.HasOne("EF_Project.Models.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Employ__5AEE82B9");

                    b.HasOne("EF_Project.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__GuestI__59FA5E80");

                    b.Navigation("Employee");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("EF_Project.Models.BookingRoom", b =>
                {
                    b.HasOne("EF_Project.Models.Employee", "AssignedEmployee")
                        .WithMany("BookingRooms")
                        .HasForeignKey("AssignedEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingRo__Assig__5FB337D6");

                    b.HasOne("EF_Project.Models.Booking", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingRo__Booki__5DCAEF64");

                    b.HasOne("EF_Project.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingRo__RoomI__5EBF139D");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EF_Project.Models.HotelRanking", b =>
                {
                    b.HasOne("EF_Project.Models.Guest", "Guest")
                        .WithMany("HotelRankings")
                        .HasForeignKey("GuestId")
                        .IsRequired()
                        .HasConstraintName("FK__HotelRank__Guest__6A30C649");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("EF_Project.Models.Payment", b =>
                {
                    b.HasOne("EF_Project.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Bookin__6E01572D");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EF_Project.Models.Room", b =>
                {
                    b.HasOne("EF_Project.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Rooms__RoomTypeI__5165187F");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("EF_Project.Services.ServiceUsage", b =>
                {
                    b.HasOne("EF_Project.Models.Booking", "Booking")
                        .WithMany("ServiceUsages")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceUs__Booki__656C112C");

                    b.HasOne("EF_Project.Services.Service", "Service")
                        .WithMany("ServiceUsages")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceUs__Servi__66603565");

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EF_Project.Models.Booking", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Payments");

                    b.Navigation("ServiceUsages");
                });

            modelBuilder.Entity("EF_Project.Models.Employee", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EF_Project.Models.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HotelRankings");
                });

            modelBuilder.Entity("EF_Project.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");
                });

            modelBuilder.Entity("EF_Project.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("EF_Project.Services.Service", b =>
                {
                    b.Navigation("ServiceUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
